# Generated by Django 5.2.6 on 2025-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(default='USER', max_length=20),
        ),
    ]
