# Generated by Django 5.2.6 on 2025-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='mô tả', max_length=255),
        ),
    ]
