# Generated by Django 6.0 on 2025-12-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_receiver_address_order_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carb_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='hint_text',
            field=models.CharField(blank=True, default='Uống ngon hơn khi lạnh', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fast_ship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_genuine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, default='7 ngày nếu lỗi', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_guide',
            field=models.TextField(blank=True, default='Bảo quản nơi khô ráo và thoáng mát.\nĐóng kín sau khi mở.\nNgon hơn khi uống lạnh.'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_short',
            field=models.CharField(blank=True, default='Nơi khô ráo, thoáng mát', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.product')),
            ],
        ),
    ]
