# Generated by Django 6.0 on 2025-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_carb_g_product_energy_kcal_product_fat_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
